<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <script src="https://kit.fontawesome.com/4514d9060c.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{{ asset('front/css/style.css') }}"/>
    <link rel="shortcut icon" href="https://res.cloudinary.com/di4ezko9l/image/upload/v1675879526/img/favicon-kdl_eyyony.png" />
    <link rel="preload" href="{{ asset('front/css/style.css') }}"/>
    <link rel="preload" href="{{ asset('front/js/script.js') }}"/>
    <title>KLUANE | PRIVACY NOTICE</title>
</head>
<body>
    @include('Pagina.components.menu-azul')
    <div class="container py-5">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-1"></div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-10">
                <div class="text-center">
                    <img src="https://res.cloudinary.com/di4ezko9l/image/upload/v1675879562/img/logo-kluane-azul_hupqix.png" alt="KLUANE" class="img-fluid mb-3"/>
                    <h1 class="txt-azul black">KLUANE DRILLING LTD PRIVACY NOTICE</h1>
                </div>
                <div class="regular txt-gris py-3">
                    <p>
                        This document constitutes the Privacy Notice for the purposes of the provisions of the Federal Law on the Protection of Personal Data in the Possession of Individuals (the "LFPDP") and the provisions emanating from it or related to it. This Privacy Notice (hereinafter referred to as "Notice") applies to personal information collected about the Holder by KLUANEDRILLING.CA in its capacity as Controller. The purpose of this Notice is to protect your personal data, through its legitimate, controlled and informed treatment, in order to guarantee your privacy, as well as your right to information self-determination.
                    </p>
                    <p>
                        In accordance with Article 3, section V of the Law, Personal Data means: Any information concerning an identified or identifiable natural person in accordance with the provisions of section I of Article 16 of the Law, will be the Responsible for your personal information (Personal Data).
                    </p>
                    <p>What information do we collect?</p>
                    <p>
                        The Manager collects information that may reasonably identify you, for example, but not limited to: your first and last name; date of birth; e-mail address, resume, general profile information.
                    </p>
                    <p>How do we use or share the information we collect?</p>
                    <p>
                        By sending via email your personal data to the different representatives of KLUANEDRILLING.CA and/or completing the online application that appears on the page, you accept and authorize KLUANEDRILLING.CA use and treat in an automated way your personal data and information provided, which will be part of our database for the purpose of using them in a declarative way, but not limited to: identify you, communicate, contact you, send you information, update our database, and promote all the artistic content generated by KLUANEDRILLING.CA
                    </p>
                    <p>
                        KLUANEDRILLING.CA, as responsible for the processing of your personal data, is obliged to comply with the principles of legality, consent, information, quality, purpose, loyalty, proportionality and responsibility protected by the Law; therefore, based on Articles 13 and 14 of the Law, KLUANEDRILLING.CA undertakes to keep your personal data strictly confidential, as well as to maintain administrative, technical and physical security measures to protect them against any damage, loss, alteration, access or unauthorized processing.
                    </p>
                    <p>How to contact our Personal Data Department?</p>
                    <p>
                        For any communication regarding our Privacy Notice, please contact our Personal Data Department: <a href="" class="a_none_style txt-azul">info@kdlmexico.com</a> 
                    </p>
                    <p>How to exercise your ARCO rights?</p>
                    <p>
                        In terms of the provisions of Article 22 of the Law, you have the right at any time to exercise your rights of access, rectification, cancellation and opposition to the processing of your personal data, by sending a request via email to info@kdlmexico.com for matters related to the Database.
                    </p>
                    <p>
                        In compliance with article 29 of the Law, this request must contain the following information: a) Your name and address or other means of communicating the response to your request; b) The documents that prove your identity or, where appropriate, the legal representation of the person making the request on your behalf; c) A clear and precise description of the personal data with respect to which you seek to exercise any of the rights mentioned in the previous paragraph, and d) Any other element or document that facilitates the location of your personal data. If you request the rectification of your personal data, you must also indicate the changes to be made and provide the documentation supporting your request. The response to your request will be communicated to you within twenty working days, counting from the date it was received, and may be extended to twenty more days in the cases established by law; to the effect that, if appropriate, the measures adopted to comply with your request will be carried out, which will take place within fifteen working days following the date on which the response is communicated.
                    </p>
                    <p>Changes to the Privacy Notice</p>
                    <p>
                        KLUANEDRILLING.CA reserves the right to periodically update this Notice to reflect changes in our information practices. It is the responsibility of the Owner to periodically review the content of the Notice where changes will be posted in conjunction with the date of the last update.
                    </p>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-1"></div>
        </div>
    </div>
    
    @include('Pagina.components.footer')
</body>
</html>